# Generated by Django 4.0.3 on 2022-06-11 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Li_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_no', models.CharField(max_length=100)),
                ('is_used', models.BooleanField(default=False)),
                ('seller_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='l_app.seller_detail')),
            ],
        ),
    ]
