# Generated by Django 4.0.3 on 2022-06-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('l_app', '0006_seller_detail_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller_detail',
            name='age',
        ),
    ]
